name: 'Submit Release'

on:
  push:
    branches: [ 'release' ]

env:
  PROJECT_FILE: src/project.godot
  VERSION_REGEX: config\/version=\"\K[0-9.\-A-z]*

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Extract version
        uses: CapsCollective/version-actions/extract-version@v1.0
        with:
          version-file: ${{ env.PROJECT_FILE }}
          version-regex: ${{ env.VERSION_REGEX }}
        id: extract-version

      - name: Update release status
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.extract-version.outputs.version-string }}
          commit: ${{ github.sha }}
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: false